# CHAP4 REPRESENTING REAL WORLD DATA WITH TENSORS

In [3]:
## 1 VISUAL DATA
import imageio
import torch

with open ("images/border_collie.jpg", "rb") as image_file:
    image_rd=imageio.read(image_file)
    img_arr=image_rd.get_data(0)
    print(img_arr.shape)
    print(image_rd.get_data(0))  #you can use this way to get the actual matrix
## the original img_arr structure is (H,W,C)

img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)
#trans to (C,H,W) is better for understanding and training (permute didn't chang the storage)
print(out.shape)
print(out)

(886, 1102, 3)
[[[106  90  93]
  [106  90  93]
  [105  89  92]
  ...
  [ 96  76  77]
  [ 96  76  77]
  [ 96  76  77]]

 [[105  89  92]
  [105  89  92]
  [104  88  91]
  ...
  [ 96  76  77]
  [ 96  76  77]
  [ 96  76  77]]

 [[103  87  90]
  [103  87  90]
  [103  87  90]
  ...
  [ 96  76  77]
  [ 96  76  77]
  [ 96  76  77]]

 ...

 [[ 43  43  35]
  [ 43  43  35]
  [ 44  44  36]
  ...
  [ 45  42  37]
  [ 45  42  37]
  [ 45  42  37]]

 [[ 44  44  42]
  [ 44  44  42]
  [ 44  44  42]
  ...
  [ 45  44  42]
  [ 45  44  42]
  [ 45  44  42]]

 [[ 41  43  42]
  [ 41  43  42]
  [ 41  43  42]
  ...
  [ 44  42  43]
  [ 44  42  43]
  [ 44  42  43]]]
torch.Size([3, 886, 1102])
tensor([[[106, 106, 105,  ...,  96,  96,  96],
         [105, 105, 104,  ...,  96,  96,  96],
         [103, 103, 103,  ...,  96,  96,  96],
         ...,
         [ 43,  43,  44,  ...,  45,  45,  45],
         [ 44,  44,  44,  ...,  45,  45,  45],
         [ 41,  41,  41,  ...,  44,  44,  44]],

        [[ 90,  90,  89,  ...,